DROP SCHEMA IF EXISTS SCORE_BOX;

CREATE SCHEMA SCORE_BOX;

SET SCHEMA SCORE_BOX;

CREATE TABLE ORGANIZATION (
  ID            INT(11) PRIMARY KEY,
  NAME          VARCHAR(50),
);

CREATE TABLE LEAGUE (
  ID            INT(11) PRIMARY KEY,
  NAME          VARCHAR(50),
  ORGANIZATION_ID INT(11)
);

CREATE TABLE TEAM (
  ID            INT(11) PRIMARY KEY,
  NAME          VARCHAR(50),
  LEAGUE_ID     INT(11)
);

CREATE TABLE USER (
  ID            INT(11) PRIMARY KEY,
  NAME          VARCHAR(50)
);

CREATE TABLE TEAM_TO_USER (
    ID          INT(11) PRIMARY KEY,
    TEAM_ID     INT(11),
    USER_ID     INT(11)
);