-- Organization configuration
INSERT INTO "SCORE_BOX"."ORGANIZATION" (ID, NAME) VALUES (1, 'FIFA');
INSERT INTO "SCORE_BOX"."ORGANIZATION" (ID, NAME) VALUES (2, 'UEFA');

-- League configuration
INSERT INTO "SCORE_BOX"."LEAGUE" (ID, NAME, ORGANIZATION_ID) VALUES (1, 'PL', 2);
INSERT INTO "SCORE_BOX"."LEAGUE" (ID, NAME, ORGANIZATION_ID) VALUES (2, 'LA LIGA', 2);
INSERT INTO "SCORE_BOX"."LEAGUE" (ID, NAME, ORGANIZATION_ID) VALUES (3, 'LIGA 1', 2);
INSERT INTO "SCORE_BOX"."LEAGUE" (ID, NAME, ORGANIZATION_ID) VALUES (4, 'SERIE A', 2);
INSERT INTO "SCORE_BOX"."LEAGUE" (ID, NAME, ORGANIZATION_ID) VALUES (5, 'BUNDESLIGA', 2);

-- Team configuration
INSERT INTO "SCORE_BOX"."TEAM" (ID, NAME, LEAGUE_ID) VALUES (1, 'Manchester United', 1);
INSERT INTO "SCORE_BOX"."TEAM" (ID, NAME, LEAGUE_ID) VALUES (2, 'Manchester City', 1);
INSERT INTO "SCORE_BOX"."TEAM" (ID, NAME, LEAGUE_ID) VALUES (3, 'Liverpool', 1);
INSERT INTO "SCORE_BOX"."TEAM" (ID, NAME, LEAGUE_ID) VALUES (4, 'Arsenal', 1);
INSERT INTO "SCORE_BOX"."TEAM" (ID, NAME, LEAGUE_ID) VALUES (5, 'Chelsea', 1);

-- User configuration
INSERT INTO "SCORE_BOX"."USER" (ID) VALUES ('');